# Generated by Django 5.2.4 on 2025-07-19 06:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0002_externaldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('metadata_schema', models.JSONField(default=dict, help_text='JSON schema defining expected metadata structure')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'db_table': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaggingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(choices=[('simple', 'Simple Mapping'), ('conditional', 'Conditional Logic'), ('script', 'Custom Script'), ('ml', 'Machine Learning')], max_length=20)),
                ('priority', models.IntegerField(default=100, help_text='Lower numbers have higher priority')),
                ('rule_config', models.JSONField(default=dict, help_text='Configuration for the rule (conditions, mappings, script code, etc.)')),
                ('conditions', models.JSONField(default=dict, help_text='Conditions that must be met for this rule to apply')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagging_rules', to='autotag.company')),
            ],
            options={
                'db_table': 'tagging_rules',
                'ordering': ['company', 'priority', 'name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TransactionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_code', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Confidence in the tagging decision (0-1)')),
                ('is_manual_override', models.BooleanField(default=False)),
                ('processing_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autotag.company')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='transactions.transaction')),
            ],
            options={
                'db_table': 'transaction_tags',
                'ordering': ['-created_at'],
                'unique_together': {('transaction', 'company')},
            },
        ),
    ]
