# Generated by Django 5.2.4 on 2025-07-19 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotag', '0001_initial'),
        ('transactions', '0002_externaldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontag',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='transactions.transaction'),
        ),
    ]
