# Generated by Django 5.2.4 on 2025-07-19 05:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50)),
                ('produce_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('ledger_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('source', models.CharField(choices=[('online', 'Online'), ('pos', 'Point of Sale'), ('mobile', 'Mobile App'), ('bank', 'Bank Transfer'), ('cash', 'Cash')], max_length=20)),
                ('jurisdiction', models.CharField(choices=[('us', 'United States'), ('ca', 'Canada'), ('uk', 'United Kingdom'), ('eu', 'European Union'), ('au', 'Australia')], max_length=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
